- hosts: k8s_masters_public,k8s_workers_public
  become: yes
  gather_facts: false
  tasks:

    - name: Disable swap (1/2)
      shell: |
        swapoff -a
      args:
        executable: /bin/bash

    - name: Disable swap (2/2)
      replace:
        path: /etc/fstab
        regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
        replace: '# \1'

    - name: Install prerequisites
      yum: 
        update_cache: true
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        state: present

    - name: Add DockerCE repository
      shell: |
        yum-config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
      args:
        executable: /bin/bash
        creates: /etc/yum.repos.d/docker-ce.repo

    - name: Install Docker
      yum:
        update_cache: true
        name:
          - docker-ce-18.06.1.ce 
        state: present

    - name: Install Docker
      shell: |
        mkdir /etc/docker
        cat << EOF > /etc/docker/daemon.json
        {
                  "exec-opts": ["native.cgroupdriver=systemd"]
        }
        EOF
      args:
        executable: /bin/bash
        creates: /etc/docker/daemon.json

    - name: Start and enable Docker
      systemd:
        name: docker
        state: started
        enabled: yes
