- hosts: k8s_masters_public, k8s_workers_public
  become: yes
  gather_facts: false
  tasks:
    - name: Letting iptables see bridged traffic
      shell: |
        cat <<EOF | sudo tee /etc/sysctl.d/k8s.conf
        net.bridge.bridge-nf-call-ip6tables = 1
        net.bridge.bridge-nf-call-iptables = 1
        EOF
        sysctl --system
      args:
        executable: /bin/bash
        creates: /etc/sysctl.d/k8s.conf

    - name: Add kubernetes repository
      shell: |
        cat <<EOF > /etc/yum.repos.d/kubernetes.repo
        [kubernetes]
        name=Kubernetes
        baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
        enabled=1
        gpgcheck=1
        repo_gpgcheck=1
        gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
        exclude=kubelet kubeadm kubectl
        EOF
      args:
        executable: /bin/bash
        creates: /etc/yum.repos.d/kubernetes.repo

    - name: Set permissive SELinux
      selinux:
        policy: targeted
        state: permissive

    - name: Set current SElinux enforce to 0
      shell: |
        setenforce 0
      args:
        executable: /bin/bash

    - name: Install prerequisites
      yum:
        state: latest
        update_cache: true
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present
        disable_excludes: kubernetes

    - name: Start and enable kubelet
      systemd:
        name: kubelet
        state: started
        enabled: yes
